export const LOAD_EXPOSURE_SUCCESS = 'LOAD_EXPOSURE_SUCCESS';
export const LOAD_FACILITY_SUCCESS = 'LOAD_FACILITY_SUCCESS';
export const LOAD_PERSON_SUCCESS = 'LOAD_PERSON_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const SAVE_SUCCESS = 'SAVE_SUCCESS';